### ISSUE TITLE
Tekst Leesbaarheid

### ISSUE THREAD

**Issue by TygoWolven** [Robin1224/nextjs-the-startup#1]
Om te beginnen ziet de pagina er heel goed uit, en lijkt alles mooi te werken voor elk scherm. 

Ik zie alleen wel problemen met sommige teksten. Deze zijn slecht leesbaar. Ik zou aanraden om deze beter leesbaar te maken door ze mogelijk dikker te maken, of de kleuren te veranderen om het contrast te verhogen. Op deze manier zal de website beter toegankelijk zijn voor een groter publiek.

![image](https://github.com/Robin1224/nextjs-the-startup/assets/144010858/faa4cfbc-6ee0-4e53-9569-4097e188f6e7)

![image](https://github.com/Robin1224/nextjs-the-startup/assets/144010858/0037db50-1b01-486e-b3e3-f4fb3c510a4e)

**Comment by Robin1224** [comment]
Ik heb voor deze sprint geprobeerd om mij zo nauw mogelijk aan het design van de opdrachtgever te houden. Hierbij was de tekst specifiek deze dikte. 

Wel ben ik het met je eens dat dit niet goed leesbaar is. Als ik meerdere sprints met de opdrachtgever zou ondergaan, dan zou ik dit bij de sprint review met ze delen en overleggen of ik het dikker kon maken. 

Omdat dit echter maar 1 sprint is, en het geen website is die echt online komt te staan maar juist een casus van de opdrachtgever om te zien hoe goed wij een design konden namaken, heb ik ervoor gekozen om dit toch zo te laten, ookal ben ik het met je eens dat het op een echte website beter zou zijn om de tekst dikker te maken.

Thanks voor de feedback! :)
