### ISSUE TITLE
Footer formaat

### ISSUE THREAD

**Issue by Khdulkadir** [Robin1224/nextjs-the-startup#2]
Footer is erg groot. Ik weet dat de opdrachtgever het zo wou, maar misschien is het toch bespreekbaar om er toch een normale footer te maken.

**Comment by Robin1224** [comment]
De opdracht was een casus vanuit de opdrachtgever die gemaakt was om verschillende vaardigheden te testen (dezelfde casus wordt bijvoorbeeld ook gebruikt bij hun internships), en daarom zijn er bepaalde designkeuzes die een beetje apart lijken. 

De opdrachtgever wou zien hoe wij een element met volledige schermgrootte zouden aanpakken, en uiteindelijk hebben zij hiervoor de footer gebruikt. Als ik het design zelf zou maken, zou ik het echter wel een stuk kleiner maken.

Uiteindelijk leek het mij niet nodig om dit hier aan te passen, omdat het echt specifiek iets is wat de opdrachtgever graag wou zien, maar alsnog ben ik het wel met je eens dat de footer kleiner zou moeten als het een echte website zou zijn. Thanks voor de feedback!
