### ISSUE TITLE
Content is breder van de pagina

### ISSUE THREAD

**Issue by Khdulkadir** [Robin1224/nextjs-the-startup#3]
Er is een horizontale scrollbar, wat betekent dat er iets in de content is wat breder is dan de pagina.

**Comment by Robin1224** [comment]
Dit issue komt bij mijzelf niet voor, dus is het lastig om te weten of het nu opgelost is of niet. Ik heb echter een width property toegevoegd op het `<body>` element van `100vw`.

```tsx
<body className="w-screen ... "> 
```

Hopelijk betekent dit dat de body nu nooit breder zal zijn dan het scherm, en dat er dit issue nu dus opgelost is.

Thanks voor het inschieten :)
